blank_issues_enabled: false
contact_links:
  - name: Discord Community
    url: https://discord.gg/eKwrtZEw
    about: Join our Discord server for questions and discussions
  - name: GitHub Discussions
    url: https://github.com/nst-sdc/site/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/nst-sdc/site#readme
    about: Check out our documentation for help and guides
